### PR TITLE
2.4 siso

### PR DESCRIPTION
**Pull request by fdege**
Hi 
we have pushed the changes for eZ Commerce/eZ Platform v2.4-beta and the meta repos is prepared as well. Can you check the repo.

Thanks 
Frank

### CODE REVIEW

**Comment by andrerom** [comment]
@fdege I guess we still need #1 right?


/fyi @vidarl: solr changes

**Comment by fdege** [comment]
@andrerom  Hm. I think we covered this topics already or did i missed something? 

- "silversolutions/silver.adminerp"
 has been added already to the composer.json 

-  ttl_com_adv is already defined in the json: 
{ "type": "composer", "url": "https://updates.ez.no/ttl_com_adv" }

**Comment by glye** [comment]
@fdege @andrerom Yes, if we merge this, we can close #1 without merge. It is outdated anyway (2.4 now, not 2.3).

**Comment by fdege** [comment]
Hi @glye hi @andrerom,

we have tested the installation using this 2.4 branch.  
We found one issue which might be connected to this pullrequest: there is no function to create a form in the backend so i am wondering if a bundle is missing. 

Maybe someone from eZ can check the composer.josn/AppKernerl to make sure that all bundles are loaded as expected.

**Comment by andrerom** [comment]
@fdege Looks ok to me, I can't validate the commerce relevant changes but I assume your team is able to do that. 

**One thing**: Should any of these changes be applied on `ezcommerce` repo? as in are any of these changes generic for both?

**Comment by andrerom** [comment]
@fdege / @silverjgo I merged this and handled conflicts in composer.json, you can see the changes here:
https://github.com/ezsystems/ezcommerce-advanced/commit/b110231714d837d34a6002754043f6af5f994e59#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780

If this is ok state for you, then please go ahead and tag a 2.4.0-betaX tag where X is a number higher than what has been made on your side so far internally. And from now on do the releases here, and then pass to product team (for QA).

**Pull request merged**
