### PR TITLE
EC-235: Fixed Solr configuration

### PR DESCRIPTION
**Pull request by alongosz**
| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | [EC-235](https://jira.ez.no/browse/EC-235)
| **Type**                                   | bug
| **Target eZ Platform version** | `v3.1`+

## TL;DR;

This PR fixes Solr configuration issues caused by SolariumBundle and Platform Solr Bundle relying on the same SOLR_DSN but expecting it in a slightly different form.

## Description    

Both bundles used by Commerce rely on the same `SOLR_DSN` environment variable. However in the case of SolariumBundle "solr" suffix is added automatically. To avoid maintaining separate variables for both bundles "/solr" suffix was explicitly added in the eZ Platform by Ibexa Solr Bundle configuration.

To have unified SOLR_DSN I also needed to set `SISO_SEARCH_SOLR_PATH` variable as empty by default. Keeping slash for this variable makes both Solarium and Platform Solr Bundle crash when accessing index because extra slash is already present there:
```
Wrong HTTP status received from Solr: 404 on http://localhost:8983//collection1
```

Additionally I've dropped duplicated `SOLR_CORE` environment variable from `.env` file (it's there, few lines further).

Configuration for Solr Bundle was duplicated in `config/packages/ezplatform_solr.yaml` and `config/packages/ezcommerce/ezcommerce_common.yaml`. Removed it from the latter one as it belongs to specific package config file. Alternative would be removing `ezplatform_solr.yaml` which is present in all other editions and thus might cause mistakes on horizontal merges.

## TODO
- [x] Create JIRA issue.

## QA
- [x] Sanities

### CODE REVIEW

**Review by micszo — APPROVED** [review]
QA Approved on EC v3.1.1.

**Comment by kmadejski** [comment]
Hi @alongosz. This change breaks installations on Platform.sh, I have created a new JIRA issue for it: https://jira.ez.no/browse/EC-238

**Comment by alongosz** [comment]
> Hi @alongosz. This change breaks installations on Platform.sh, I have created a new JIRA issue for it: https://jira.ez.no/browse/EC-238

Well... This means that P.sh configuration does some incorrect magic that is not its responsibility. How can I reproduce this myself? I'm not P.sh user, tried this once I think but don't remember much.

**Comment by lserwatka** [comment]
We need to fix it urgently.

**Comment by kmadejski** [comment]
I did some little research, it seems that since we added `solr` part to the DSN in YAML config, we should remove it from this script that builds varialbes on P.sh: https://github.com/ezsystems/ezcommerce/blob/master/config/packages/overrides/platformsh.php#L115

> How can I reproduce this myself? I'm not P.sh user, tried this once I think but don't remember much.

Create a new P.sh instance with clean eZ Commerce. It will break right after on the front-end or when you try to access AdminUI. Before you waste time on this, let me check whether fixing mentioned script helps 🙂 

Fix proposed in: https://github.com/ezsystems/ezcommerce/pull/29

**Pull request merged**
